# Generated by Django 5.0 on 2023-12-29 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_optimizer', '0003_customuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default=datetime.datetime(2023, 12, 29, 10, 12, 3, 204596, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_spend',
            field=models.CharField(choices=[('<$10,000', '<$10,000'), ('$10,000 to $100,000', '$10,000 to $100,000'), ('$100,001 to $250,000', '$100,001 to $250,000'), ('$250,001 to $500,000', '$250,001 to $500,000'), ('> $500,001', '> $500,001')], default='<$10,000', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
    ]
