# Generated by Django 5.0 on 2023-12-29 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_optimizer', '0004_remove_customuser_full_name_customuser_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hear_about_us',
            field=models.CharField(default=datetime.datetime(2023, 12, 29, 11, 6, 8, 247940, tzinfo=datetime.timezone.utc), max_length=200),
            preserve_default=False,
        ),
    ]
